#!/bin/bash
set -euo pipefail
trap 'echo "script error: $(basename "$BASH_SOURCE"):$LINENO $BASH_COMMAND" >&2' ERR
script_dir="$(dirname -- "$(readlink -f -- "$0")")"

which asdf &>/dev/null || . "$HOME/.asdf/asdf.sh" || echo "asdf is not installed, using local java binary" >&2

java -jar "$script_dir/target/scala-2.13/tinycc.jar" "$@" || exit $?
